import { logger } from '../config/logger';

interface SiteverifySuccess {
  success: boolean;
  'error-codes'?: string[];
}

/**
 * Cloudflare's official always-passes test key pair (safe to hard-code — publicly documented).
 * Site key:   1x00000000000000000000AA
 * Secret key: 1x0000000000000000000000000000000AA
 * @see https://developers.cloudflare.com/turnstile/troubleshooting/testing/
 */
const CF_TEST_SECRET = '1x0000000000000000000000000000000AA';

/**
 * Validates a Cloudflare Turnstile token server-side.
 * In non-production environments the dev test secret key is used as a fallback so that
 * tokens generated by the always-passes test site key (1x00000000000000000000AA) are
 * accepted without requiring a real Cloudflare widget setup.
 * @see https://developers.cloudflare.com/turnstile/get-started/server-side-validation/
 */
export async function verifyTurnstileToken(token: string | undefined, remoteip?: string): Promise<boolean> {
  const configuredSecret = process.env.CLOUDFLARE_TURNSTILE_SECRET_KEY?.trim();
  const isProd = process.env.NODE_ENV === 'production';

  // Determine which secret to use:
  //   - Production: require CLOUDFLARE_TURNSTILE_SECRET_KEY and fail hard if missing.
  //   - Development/staging: fall back to the Cloudflare always-passes test secret when the
  //     configured secret is absent OR when the frontend is using the dev test site key.
  let secret: string;
  if (isProd) {
    if (!configuredSecret) {
      logger.error('CLOUDFLARE_TURNSTILE_SECRET_KEY is unset in production — blocking request');
      return false;
    }
    secret = configuredSecret;
  } else {
    if (!configuredSecret) {
      logger.warn('CLOUDFLARE_TURNSTILE_SECRET_KEY is unset — using Cloudflare test secret for dev');
      secret = CF_TEST_SECRET;
    } else {
      secret = configuredSecret;
    }
  }

  const raw = typeof token === 'string' ? token.trim() : '';
  if (!raw) {
    logger.warn('Turnstile verification: no token provided');
    return false;
  }

  const body = new URLSearchParams();
  body.set('secret', secret);
  body.set('response', raw);
  if (remoteip) body.set('remoteip', remoteip);

  try {
    const res = await fetch('https://challenges.cloudflare.com/turnstile/v0/siteverify', {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: body.toString(),
    });

    if (!res.ok) {
      logger.warn('Turnstile siteverify HTTP error', { status: res.status });
      // In development, allow through on network errors so local testing isn't blocked.
      return !isProd;
    }

    const data = (await res.json()) as SiteverifySuccess;
    if (!data.success) {
      logger.warn('Turnstile verification failed', { codes: data['error-codes'], isProd });
      // If in dev and the configured production secret rejected the dev token, retry with the
      // Cloudflare test secret so the dev workflow is unblocked.
      if (!isProd && secret !== CF_TEST_SECRET) {
        logger.info('Turnstile: retrying with Cloudflare dev test secret');
        const retryBody = new URLSearchParams();
        retryBody.set('secret', CF_TEST_SECRET);
        retryBody.set('response', raw);
        const retryRes = await fetch('https://challenges.cloudflare.com/turnstile/v0/siteverify', {
          method: 'POST',
          headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
          body: retryBody.toString(),
        });
        if (retryRes.ok) {
          const retryData = (await retryRes.json()) as SiteverifySuccess;
          if (retryData.success) {
            logger.info('Turnstile: dev test secret verified successfully');
            return true;
          }
        }
      }
    }
    return Boolean(data.success);
  } catch (err) {
    logger.warn('Turnstile siteverify request threw', { error: String(err) });
    // In development, allow through on connectivity errors.
    return !isProd;
  }
}
